version: 0.0.1
name: highcharts_flutter_webwebview
description: Optimised Flutter webview for web target with Highcharts.
homepage: https://www.highcharts.com/integrations/
issue_tracker: https://github.com/highcharts/highcharts_flutter/issues
repository: https://github.com/highcharts/highcharts_flutter

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      web:
        pluginClass: HighchartsWebWebViewPlatform
        fileName: highcharts_flutter_webwebview.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ">=1.0.0 <2.0.0"
  webview_flutter_platform_interface: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

topics:
  - html
  - webview
  - webview-flutter
